/*
 * Glypdl - Media Downloader
 * Copyright (C) 2024 Glypdl Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */
package com.glypdl.android.service.auth

import android.content.Context
import android.net.Uri
import dagger.hilt.android.qualifiers.ApplicationContext
import java.io.File
import java.io.FileWriter
import java.util.Locale
import javax.inject.Inject
import javax.inject.Singleton

data class AuthPlatform(
    val id: String,
    val name: String,
    val domain: String,
    val loginUrl: String
)

@Singleton
class AuthCookieManager @Inject constructor(
    @ApplicationContext private val context: Context
) {
    private val cookiesDir = File(context.filesDir, "cookies").apply {
        if (!exists()) mkdirs()
    }

    companion object {
        val SUPPORTED_PLATFORMS = listOf(
            AuthPlatform(
                id = "instagram",
                name = "Instagram",
                domain = "instagram.com",
                loginUrl = "https://www.instagram.com/accounts/login/"
            ),
            AuthPlatform(
                id = "facebook",
                name = "Facebook",
                domain = "facebook.com",
                loginUrl = "https://www.facebook.com/login/"
            ),
            AuthPlatform(
                id = "youtube",
                name = "YouTube / Google",
                domain = "youtube.com",
                loginUrl = "https://accounts.google.com/ServiceLogin?service=youtube"
            ),
            AuthPlatform(
                id = "tiktok",
                name = "TikTok",
                domain = "tiktok.com",
                loginUrl = "https://www.tiktok.com/login"
            ),
            AuthPlatform(
                id = "twitter",
                name = "X (Twitter)",
                domain = "twitter.com",
                loginUrl = "https://twitter.com/i/flow/login"
            )
        )
    }

    fun resolveDomainKey(urlOrHost: String): String {
        val host = try {
            val uri = Uri.parse(if (urlOrHost.contains("://")) urlOrHost else "https://$urlOrHost")
            uri.host ?: urlOrHost
        } catch (e: Exception) {
            urlOrHost
        }.lowercase(Locale.ROOT)

        return when {
            host.contains("instagram.com") -> "instagram.com"
            host.contains("youtube.com") || host.contains("youtu.be") -> "youtube.com"
            host.contains("tiktok.com") -> "tiktok.com"
            host.contains("twitter.com") || host.contains("x.com") -> "twitter.com"
            host.contains("facebook.com") || host.contains("fb.watch") -> "facebook.com"
            else -> {
                val parts = host.split(".")
                if (parts.size >= 2) {
                    "${parts[parts.size - 2]}.${parts[parts.size - 1]}"
                } else {
                    host
                }
            }
        }
    }

    fun saveCookies(domainKey: String, rawCookies: String): Boolean {
        if (rawCookies.isBlank()) return false

        val cookieFile = File(cookiesDir, "${domainKey}.txt")
        try {
            val dotDomain = if (domainKey.startsWith(".")) domainKey else ".$domainKey"
            val expiry = (System.currentTimeMillis() / 1000) + (10L * 365 * 24 * 3600)

            FileWriter(cookieFile, false).use { writer ->
                writer.write("# Netscape HTTP Cookie File\n")
                writer.write("# https://curl.se/docs/http-cookies.html\n")
                writer.write("# Generated by Glypdl. Do not edit.\n\n")

                val pairs = rawCookies.split(";").map { it.trim() }
                for (pair in pairs) {
                    if (pair.isBlank() || !pair.contains("=")) continue
                    val name = pair.substringBefore("=").trim()
                    val value = pair.substringAfter("=").trim()
                    if (name.isNotEmpty()) {
                        writer.write("$dotDomain\tTRUE\t/\tTRUE\t$expiry\t$name\t$value\n")
                    }
                }
            }
            return cookieFile.exists() && cookieFile.length() > 0
        } catch (e: Exception) {
            e.printStackTrace()
            return false
        }
    }

    fun getCookieFile(urlOrDomain: String): File? {
        val key = resolveDomainKey(urlOrDomain)
        val file = File(cookiesDir, "${key}.txt")
        return if (file.exists() && file.length() > 0) file else null
    }

    fun hasCookies(domainKey: String): Boolean {
        return getCookieFile(domainKey) != null
    }

    fun clearCookies(domainKey: String): Boolean {
        val file = File(cookiesDir, "${domainKey}.txt")
        return if (file.exists()) file.delete() else true
    }

    fun clearAllCookies() {
        cookiesDir.listFiles()?.forEach { it.delete() }
    }

    fun getSavedDomains(): List<String> {
        return cookiesDir.listFiles()
            ?.filter { it.isFile && it.extension == "txt" && it.length() > 0 }
            ?.map { it.nameWithoutExtension }
            ?.sorted()
            ?: emptyList()
    }
}
