import { extractDomain } from './utils';

function getBrowserApi(): any {
  // @ts-expect-error browser runtime
  return typeof browser !== 'undefined' ? browser : typeof chrome !== 'undefined' ? chrome : null;
}

export interface CookieLike {
  domain: string;
  name: string;
  value: string;
  path?: string;
  secure?: boolean;
  httpOnly?: boolean;
  hostOnly?: boolean;
  expirationDate?: number;
}

/**
 * Format a list of browser cookies into the standard Netscape HTTP Cookie File format.
 * Never logs or exposes cookie contents.
 */
export function formatNetscapeCookies(cookies: CookieLike[]): string {
  const lines = [
    '# Netscape HTTP Cookie File',
    '# http://curl.haxx.se/rfc/cookie_spec.html',
    '# This file was generated by Glypdl. Do not edit.',
    ''
  ];

  for (const c of cookies) {
    if (!c || !c.name) continue;
    let domain = c.domain || '';
    const isSubdomain = domain.startsWith('.') || c.hostOnly === false;
    if (isSubdomain && !domain.startsWith('.')) {
      domain = `.${domain}`;
    }
    const includeSubdomains = isSubdomain ? 'TRUE' : 'FALSE';
    const path = c.path || '/';
    const secure = c.secure ? 'TRUE' : 'FALSE';
    const expires = c.expirationDate && c.expirationDate > 0 ? Math.round(c.expirationDate) : 0;
    const prefix = c.httpOnly ? '#HttpOnly_' : '';
    const name = c.name;
    const value = c.value || '';

    lines.push(`${prefix}${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expires}\t${name}\t${value}`);
  }

  return lines.join('\n') + '\n';
}

/**
 * Extract cookies strictly for the target URL's domain upon explicit user action.
 * Supports Firefox / LibreWolf Total Cookie Protection (partitionKey), container tabs (storeId),
 * and client-side domain matching fallback.
 * Returns Netscape cookie file content.
 */
export async function extractTargetCookies(targetUrl: string, storeId?: string): Promise<string> {
  const browserApi = getBrowserApi();
  if (!browserApi?.cookies?.getAll) {
    throw new Error('Browser cookies API is not available or permission was denied.');
  }

  let domain = extractDomain(targetUrl);
  if (domain.includes('fbcdn.net') || domain.includes('cdninstagram.com') || domain.includes('instagram.com')) {
    domain = 'instagram.com';
  } else if (domain.includes('googlevideo.com') || domain.includes('youtube.com') || domain.includes('youtu.be')) {
    domain = 'youtube.com';
  } else if (
    domain.includes('tiktokcdn.com') ||
    domain.includes('byteoversea.com') ||
    domain.includes('ibytedtos.com') ||
    domain.includes('tiktok.com')
  ) {
    domain = 'tiktok.com';
  } else if (domain.includes('twimg.com') || domain.includes('twitter.com') || domain.includes('x.com')) {
    domain = 'x.com';
  }

  const cleanDomain = domain ? domain.replace(/^www\./, '').toLowerCase() : '';
  const cookies: CookieLike[] = [];

  const addCookies = (newCookies: CookieLike[]) => {
    if (!Array.isArray(newCookies)) return;
    for (const nc of newCookies) {
      if (!nc || !nc.name) continue;
      const cDomain = (nc.domain || '').replace(/^\./, '').toLowerCase();
      if (cleanDomain) {
        const isMatch =
          cDomain === cleanDomain ||
          cDomain.endsWith(`.${cleanDomain}`) ||
          cleanDomain.endsWith(`.${cDomain}`);
        if (!isMatch) continue;
      }
      if (!cookies.some((c) => c.name === nc.name && c.domain === nc.domain && c.path === nc.path)) {
        cookies.push(nc);
      }
    }
  };

  const safeGetAll = async (query: any) => {
    try {
      const res = await browserApi.cookies.getAll(query);
      if (Array.isArray(res)) {
        addCookies(res);
      }
    } catch {
      // Ignored for unsupported query fields (e.g. partitionKey on older engines)
    }
  };

  // Collect candidate store IDs to check
  const storeCandidates: (string | undefined)[] = [storeId];
  if (storeId !== undefined) {
    storeCandidates.push(undefined); // Try without specific storeId as fallback
  }

  // Also query known cookie stores if available
  if (browserApi?.cookies?.getAllCookieStores) {
    try {
      const stores = await browserApi.cookies.getAllCookieStores();
      if (Array.isArray(stores)) {
        for (const s of stores) {
          if (s && s.id && !storeCandidates.includes(s.id)) {
            storeCandidates.push(s.id);
          }
        }
      }
    } catch {
      // Ignored
    }
  }

  // Iterate candidate stores until we find cookies
  for (const currentStoreId of storeCandidates) {
    const baseQueries: any[] = [];
    const baseObj = currentStoreId ? { storeId: currentStoreId } : {};

    // In Firefox / LibreWolf with dFPI (Dynamic First-Party Isolation / Total Cookie Protection),
    // partitionKey: {} queries both partitioned and unpartitioned cookies.
    // Try both with partitionKey: {} and without it.
    baseQueries.push({ ...baseObj, partitionKey: {} });
    baseQueries.push({ ...baseObj });

    for (const bq of baseQueries) {
      // 1. Query by clean domain and domain with leading dot
      if (cleanDomain) {
        await safeGetAll({ ...bq, domain: cleanDomain });
        await safeGetAll({ ...bq, domain: `.${cleanDomain}` });
      }

      // 2. Query by target URL
      if (targetUrl && targetUrl.startsWith('http')) {
        await safeGetAll({ ...bq, url: targetUrl });
      }

      // 3. Query canonical root and www URLs
      if (cleanDomain) {
        await safeGetAll({ ...bq, url: `https://${cleanDomain}/` });
        await safeGetAll({ ...bq, url: `https://www.${cleanDomain}/` });
      }

      // 4. Broad store query fallback with client-side domain matching
      if (cookies.length === 0) {
        await safeGetAll({ ...bq });
      }

      if (cookies.length > 0) {
        break;
      }
    }

    if (cookies.length > 0) {
      break;
    }
  }

  if (!cookies || cookies.length === 0) {
    throw new Error(
      `No active cookies found for ${cleanDomain || domain || 'this website'}. Please ensure you are logged in.`
    );
  }

  return formatNetscapeCookies(cookies);
}
