import { extractDomain } from './utils';

// @ts-expect-error browser runtime
const browserApi = typeof browser !== 'undefined' ? browser : typeof chrome !== 'undefined' ? chrome : null;

export interface CookieLike {
  domain: string;
  name: string;
  value: string;
  path?: string;
  secure?: boolean;
  httpOnly?: boolean;
  expirationDate?: number;
}

/**
 * Format a list of browser cookies into the standard Netscape HTTP Cookie File format.
 * Never logs or exposes cookie contents.
 */
export function formatNetscapeCookies(cookies: CookieLike[]): string {
  const lines = [
    '# Netscape HTTP Cookie File',
    '# http://curl.haxx.se/rfc/cookie_spec.html',
    '# This file was generated by Glypdl. Do not edit.',
    ''
  ];

  for (const c of cookies) {
    if (!c || !c.name) continue;
    let domain = c.domain || '';
    const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const path = c.path || '/';
    const secure = c.secure ? 'TRUE' : 'FALSE';
    const expires = c.expirationDate && c.expirationDate > 0 ? Math.round(c.expirationDate) : 0;
    const name = c.name;
    const value = c.value || '';

    lines.push(`${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expires}\t${name}\t${value}`);
  }

  return lines.join('\n') + '\n';
}

/**
 * Extract cookies strictly for the target URL's domain upon explicit user action.
 * Returns Netscape cookie file content.
 */
export async function extractTargetCookies(targetUrl: string): Promise<string> {
  if (!browserApi?.cookies?.getAll) {
    throw new Error('Browser cookies API is not available or permission was denied.');
  }

  const domain = extractDomain(targetUrl);
  const cookies: CookieLike[] = [];

  try {
    // 1. Query cookies matching the base domain (e.g. youtube.com or .youtube.com)
    if (domain) {
      const cleanDomain = domain.replace(/^www\./, '');
      const domainCookies = await browserApi.cookies.getAll({ domain: cleanDomain });
      if (Array.isArray(domainCookies)) {
        cookies.push(...domainCookies);
      }
    }

    // 2. Also query cookies specific to the target URL to capture path-specific or host-only cookies
    try {
      const urlCookies = await browserApi.cookies.getAll({ url: targetUrl });
      if (Array.isArray(urlCookies)) {
        for (const uc of urlCookies) {
          if (!cookies.some((c) => c.name === uc.name && c.domain === uc.domain && c.path === uc.path)) {
            cookies.push(uc);
          }
        }
      }
    } catch {
      // Ignored for restricted or special scheme URLs
    }
  } catch (err: any) {
    throw new Error(`Failed to extract cookies for ${domain || targetUrl}: ${err?.message || err}`);
  }

  if (!cookies || cookies.length === 0) {
    throw new Error(`No active cookies found for ${domain || 'this website'}. Please ensure you are logged in.`);
  }

  return formatNetscapeCookies(cookies);
}
